name: Release

on:
  push:
    branches: [main, release, release-beta]
  pull_request:
    branches: [main, release, release-beta]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node.js environment
      uses: actions/setup-node@v4.0.2
      with:
        node-version: 20

    - name: Install dependencies
      run: npx ci

    - name: Install semantic-release extra plugins
      run: npm install --save-dev @semantic-release/changelog @semantic-release/git

    - name: Lint
      run: npm run lint

    # Need to fix jest to run on this workflow
    # ✖ jest --verbose --bail --findRelatedTests:
    #  No tests found, exiting with code 1
    #  Run with `--passWithNoTests` to exit with code 0
    #  No files found in /home/runner/work/z-indexify/z-indexify.
    #  Make sure Jest's configuration does not exclude this directory.

    # - name: Test
    #   run: npm run test

    - name: Build
      run: npm run build

    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: npx semantic-release
